config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'books/new'
root to: 'books#top'


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'top' => 'books#top'

post 'books' => 'books#create'

get 'books' => 'books#index'

get 'books/:id' => 'books#show', as: 'book'

get 'books/:id/edit' => 'books#edit', as: 'edit_book'

patch 'books/:id' => 'books#update', as: 'update_book'

delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end
  def create
  @book = Book.new(book_params)
  if @book.save
  redirect_to book_path(@book.id), notice: "Book was successfully updated."
else
  @books = Book.all
  render action: :index
end
end

def index
  @book = Book.new
  @books = Book.all
end

def show
  @book = Book.find(params[:id])
end

def edit
    @book = Book.find(params[:id])
end

def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
  redirect_to book_path(@book.id), notice: "Book was successfully updated."
  end
end

def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to books_path
end

private

def book_params
  params.require(:book).permit(:title, :body)
end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

<p>Title</p>
<%= f.text_field :title %>
<p>Body</p>
<%= f.text_area :body %>
<%= f.submit 'Update Book' %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "back", books_path %>
<% end %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h1>Books</h1>

<table >
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

  <% @books.each do |book| %>

    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destory", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    </tr>

<% end %>
</table>



<h2>New book</h2>

<%= form_for(@book, url: '/books') do |f| %>

<% if @book.errors.any? %>
<h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %><br>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h6>Title:</h6><p><%= @book.title %></p>

<h6>Body:</h6><p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ　Bookersへ!</h1>

<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>